nome_completo = str(input("Digite seu nome completo: ")).strip()
primeiro_nome = nome_completo.split()
espaços = nome_completo.count(" ")
print("Analisando seu nome...")
print(f"Seu nome em maiúsculas é {nome_completo.upper()} ")
print(f"Seu nome em minúsculas é {nome_completo.lower()}")
print(f"Ao todo seu nome tem {len(nome_completo) - espaços} letras")
print(f"Seu primeiro nome é {primeiro_nome[0]}")
print(f"Seu primeiro nome tem {len(primeiro_nome[0])} letras")
